# refer to src/sal/config.py for more options

approach: best_of_n
n: 16
search_batch_size: 2
sort_completed: true
filter_duplicates: true
# num_samples: 10         # REMOVE THIS LINE TO RUN ON THE WHOLE DATASET
seed: 0
model_path: "meta-llama/Llama-3.2-1B-Instruct"
prm_path: "RLHFlow/Llama3.1-8B-PRM-Deepseek-Data"
gpu_memory_utilization: 0.4